ENDPOINTS = {
    "app_feature_list": {
        "label": "App Feature - Listar funcionalidades",
        "method": "GET",
        "required": ["mailbox"],
        "optional": [],
    },
    "app_feature_get": {
        "label": "App Feature - Consultar funcionalidade",
        "method": "GET",
        "required": ["mailbox", "feature"],
        "optional": [],
    },
    "app_feature_enable": {
        "label": "App Feature - Habilitar funcionalidade",
        "method": "POST",
        "required": ["mailbox", "feature"],
        "optional": [],
    },
    "app_feature_disable": {
        "label": "App Feature - Desabilitar funcionalidade",
        "method": "DELETE",
        "required": ["mailbox", "feature"],
        "optional": [],
    },
    "mailbox_list": {
        "label": "Caixa Postal - Listar caixas",
        "method": "GET",
        "required": [],
        "optional": ["query"],
    },
    "mailbox_get": {
        "label": "Caixa Postal - Recuperar informacoes",
        "method": "GET",
        "required": ["mailbox"],
        "optional": [],
    },
    "mailbox_create": {
        "label": "Caixa Postal - Criar",
        "method": "POST",
        "required": ["mail", "displayname", "password", "accounttype"],
        "optional": [],
    },
    "mailbox_update_password": {
        "label": "Caixa Postal - Atualizar senha",
        "method": "PUT",
        "required": ["mailbox", "password"],
        "optional": ["forcepasswordchange"],
    },
    "mailbox_update_status": {
        "label": "Caixa Postal - Atualizar status",
        "method": "PUT",
        "required": ["mailbox", "accountstatus"],
        "optional": [],
    },
    "mailbox_update_title": {
        "label": "Caixa Postal - Atualizar cargo (title)",
        "method": "PUT",
        "required": ["mailbox"],
        "optional": ["title"],
    },
    "mailbox_add_alias": {
        "label": "Caixa Postal - Adicionar alias",
        "method": "PUT",
        "required": ["mailbox", "alias"],
        "optional": [],
    },
    "mailbox_remove_alias": {
        "label": "Caixa Postal - Remover alias",
        "method": "PUT",
        "required": ["mailbox", "alias"],
        "optional": [],
    },
    "mailbox_update_product": {
        "label": "Caixa Postal - Atualizar produto",
        "method": "PUT",
        "required": ["mailbox", "accounttype"],
        "optional": ["confirm_purchase"],
    },
    "mailbox_update_generic": {
        "label": "Caixa Postal - Atualizar campos livres",
        "method": "PUT",
        "required": ["mailbox"],
        "optional": ["data_kv"],
    },
    "mailbox_rename": {
        "label": "Caixa Postal - Renomear",
        "method": "PUT",
        "required": ["mailbox", "novo_mail"],
        "optional": [],
    },
    "mailbox_delete": {
        "label": "Caixa Postal - Excluir",
        "method": "DELETE",
        "required": ["mailbox"],
        "optional": [],
    },
    "mailbox_remove_all_aliases": {
        "label": "Caixa Postal - Remover todos aliases",
        "method": "DELETE",
        "required": ["mailbox"],
        "optional": [],
    },
    "custom_field_list": {
        "label": "Custom Field - Listar campos",
        "method": "GET",
        "required": ["mailbox"],
        "optional": [],
    },
    "custom_field_create": {
        "label": "Custom Field - Criar campo",
        "method": "POST",
        "required": ["mailbox", "name", "value"],
        "optional": [],
    },
    "custom_field_update": {
        "label": "Custom Field - Atualizar campo",
        "method": "PUT",
        "required": ["mailbox", "field_name", "value"],
        "optional": [],
    },
    "custom_field_delete": {
        "label": "Custom Field - Excluir campo",
        "method": "DELETE",
        "required": ["mailbox", "field_name"],
        "optional": [],
    },
    "deleted_list": {
        "label": "Deletadas - Listar caixas deletadas",
        "method": "GET",
        "required": [],
        "optional": ["filters_email"],
    },
    "deleted_get": {
        "label": "Deletadas - Recuperar informacoes",
        "method": "GET",
        "required": ["mailbox"],
        "optional": [],
    },
    "deleted_restore": {
        "label": "Deletadas - Restaurar caixa",
        "method": "PUT",
        "required": ["mailbox"],
        "optional": [],
    },
    "deleted_remove": {
        "label": "Deletadas - Remover permanentemente",
        "method": "DELETE",
        "required": ["mailbox"],
        "optional": [],
    },
    # ── Caixas Postais - Retencao e Bloqueio ──────────────────
    "mailbox_batch_retention": {
        "label": "Caixa Postal - Retencao em lote (JSON)",
        "method": "POST",
        "required": ["mailbox", "rule_folder", "rule_policy", "rule_days"],
        "optional": [],
    },
    "mailbox_block_period_get": {
        "label": "Caixa Postal - Consultar bloqueio por periodo",
        "method": "GET",
        "required": ["mailbox"],
        "optional": [],
    },
    "mailbox_block_period_create": {
        "label": "Caixa Postal - Criar bloqueio por periodo",
        "method": "POST",
        "required": ["mailbox"],
        "optional": [],
    },
    "mailbox_block_period_delete": {
        "label": "Caixa Postal - Remover bloqueio por periodo",
        "method": "DELETE",
        "required": ["mailbox"],
        "optional": [],
    },
    # ── Restaurar mensagens ────────────────────────────────────
    "mailbox_backup_list": {
        "label": "Restaurar - Listar backups da caixa",
        "method": "GET",
        "required": ["mailbox"],
        "optional": ["page", "perPage", "dateFrom", "dateTo"],
    },
    "mailbox_backup_folders": {
        "label": "Restaurar - Listar pastas do backup",
        "method": "GET",
        "required": ["mailbox", "backup_id"],
        "optional": [],
    },
    "mailbox_backup_restore": {
        "label": "Restaurar - Restaurar mensagens (JSON)",
        "method": "POST",
        "required": ["mailbox", "backup_id"],
        "optional": ["restoreFolders", "restoreDestination"],
    },
    "mailbox_backup_history": {
        "label": "Restaurar - Historico de restauracoes",
        "method": "GET",
        "required": ["mailbox"],
        "optional": ["page", "perPage", "status"],
    },
    # ── Dominios ──────────────────────────────────────────────
    "domain_list": {
        "label": "Dominio - Listar dominios",
        "method": "GET",
        "required": [],
        "optional": ["query"],
    },
    "domain_get": {
        "label": "Dominio - Recuperar informacoes",
        "method": "GET",
        "required": ["domain"],
        "optional": [],
    },
    "domain_create": {
        "label": "Dominio - Criar dominio",
        "method": "POST",
        "required": ["domain"],
        "optional": [],
    },
    "domain_update": {
        "label": "Dominio - Atualizar informacoes",
        "method": "PUT",
        "required": ["domain"],
        "optional": ["forcepasswordchange", "status", "data_kv"],
    },
    "domain_delete": {
        "label": "Dominio - Excluir dominio",
        "method": "DELETE",
        "required": ["domain"],
        "optional": [],
    },
    "domain_mail_products": {
        "label": "Dominio - Produtos disponiveis",
        "method": "GET",
        "required": ["domain"],
        "optional": [],
    },
    "domain_app_feature_list": {
        "label": "Dominio - App Feature - Listar",
        "method": "GET",
        "required": ["domain"],
        "optional": [],
    },
    "domain_app_feature_get": {
        "label": "Dominio - App Feature - Consultar",
        "method": "GET",
        "required": ["domain", "feature"],
        "optional": [],
    },
    "domain_app_feature_enable": {
        "label": "Dominio - App Feature - Habilitar",
        "method": "POST",
        "required": ["domain", "feature"],
        "optional": [],
    },
    "domain_app_feature_disable": {
        "label": "Dominio - App Feature - Desabilitar",
        "method": "DELETE",
        "required": ["domain", "feature"],
        "optional": [],
    },
    "domain_property_add": {
        "label": "Dominio - Propriedade - Cadastrar",
        "method": "POST",
        "required": ["domain", "client_id"],
        "optional": [],
    },
    "domain_property_check": {
        "label": "Dominio - Propriedade - Verificar",
        "method": "GET",
        "required": ["domain", "client_id"],
        "optional": [],
    },
    # ── Grupos de e-mail ──────────────────────────────────────
    "group_list": {
        "label": "Grupo - Listar grupos",
        "method": "GET",
        "required": [],
        "optional": ["query"],
    },
    "group_get": {
        "label": "Grupo - Recuperar informacoes",
        "method": "GET",
        "required": ["group_mail"],
        "optional": [],
    },
    "group_create": {
        "label": "Grupo - Criar grupo",
        "method": "POST",
        "required": ["group_mail", "displayname"],
        "optional": [],
    },
    "group_update": {
        "label": "Grupo - Atualizar informacoes",
        "method": "PUT",
        "required": ["group_mail"],
        "optional": ["data_kv"],
    },
    "group_delete": {
        "label": "Grupo - Excluir grupo",
        "method": "DELETE",
        "required": ["group_mail"],
        "optional": [],
    },
    # ── Clientes ──────────────────────────────────────────────
    "client_list": {
        "label": "Cliente - Listar clientes",
        "method": "GET",
        "required": [],
        "optional": ["query", "page", "perPage"],
    },
    "client_get": {
        "label": "Cliente - Recuperar informacoes",
        "method": "GET",
        "required": ["client_id"],
        "optional": [],
    },
    "client_create": {
        "label": "Cliente - Criar cliente",
        "method": "POST",
        "required": ["client_name", "taxNumber", "parentId"],
        "optional": [],
    },
    "client_block": {
        "label": "Cliente - Bloquear",
        "method": "PUT",
        "required": ["client_id"],
        "optional": ["reason"],
    },
    "client_unblock": {
        "label": "Cliente - Desbloquear",
        "method": "PUT",
        "required": ["client_id"],
        "optional": [],
    },
    "client_product_list": {
        "label": "Cliente - Produtos - Listar",
        "method": "GET",
        "required": ["client_id"],
        "optional": [],
    },
    "client_product_get": {
        "label": "Cliente - Produtos - Recuperar",
        "method": "GET",
        "required": ["client_id", "product_id"],
        "optional": [],
    },
    "client_product_create": {
        "label": "Cliente - Produtos - Contratar",
        "method": "POST",
        "required": ["client_id", "product", "amount"],
        "optional": [],
    },
    "client_product_update": {
        "label": "Cliente - Produtos - Modificar quantidade",
        "method": "PUT",
        "required": ["client_id", "product_id", "amount"],
        "optional": [],
    },
    "client_product_delete": {
        "label": "Cliente - Produtos - Remover contratacao",
        "method": "DELETE",
        "required": ["client_id", "product_id"],
        "optional": [],
    },
    "client_app_feature_list": {
        "label": "Cliente - App Feature - Listar",
        "method": "GET",
        "required": ["client_id"],
        "optional": [],
    },
    "client_app_feature_get": {
        "label": "Cliente - App Feature - Consultar",
        "method": "GET",
        "required": ["client_id", "feature"],
        "optional": [],
    },
    "client_app_feature_enable": {
        "label": "Cliente - App Feature - Habilitar",
        "method": "POST",
        "required": ["client_id", "feature"],
        "optional": [],
    },
    "client_app_feature_disable": {
        "label": "Cliente - App Feature - Desabilitar",
        "method": "DELETE",
        "required": ["client_id", "feature"],
        "optional": [],
    },
    "client_custom_field_list": {
        "label": "Cliente - Campo Personalizado - Listar",
        "method": "GET",
        "required": ["client_id"],
        "optional": [],
    },
    "client_custom_field_create": {
        "label": "Cliente - Campo Personalizado - Criar",
        "method": "POST",
        "required": ["client_id", "name", "cf_label", "cf_type"],
        "optional": [],
    },
    "client_custom_field_update": {
        "label": "Cliente - Campo Personalizado - Atualizar",
        "method": "PUT",
        "required": ["client_id", "field_name", "cf_label", "cf_type"],
        "optional": [],
    },
    "client_custom_field_delete": {
        "label": "Cliente - Campo Personalizado - Excluir",
        "method": "DELETE",
        "required": ["client_id", "field_name"],
        "optional": [],
    },
    "client_webhook_list": {
        "label": "Cliente - WebHook - Listar",
        "method": "GET",
        "required": ["client_id"],
        "optional": ["filters_httpMethod"],
    },
    "client_webhook_get": {
        "label": "Cliente - WebHook - Recuperar",
        "method": "GET",
        "required": ["client_id", "webhook_id"],
        "optional": [],
    },
    "client_webhook_responses": {
        "label": "Cliente - WebHook - Respostas",
        "method": "GET",
        "required": ["client_id", "webhook_id"],
        "optional": [],
    },
    "client_webhook_create": {
        "label": "Cliente - WebHook - Cadastrar",
        "method": "POST",
        "required": ["client_id", "url", "httpMethod", "webHook"],
        "optional": [],
    },
    "client_webhook_update": {
        "label": "Cliente - WebHook - Atualizar",
        "method": "PUT",
        "required": ["client_id", "webhook_id", "url", "httpMethod", "webHook"],
        "optional": [],
    },
    "client_webhook_delete": {
        "label": "Cliente - WebHook - Excluir",
        "method": "DELETE",
        "required": ["client_id", "webhook_id"],
        "optional": [],
    },
    # ── Hospedagem ────────────────────────────────────────────
    "hosting_list": {
        "label": "Hospedagem - Listar sites",
        "method": "GET",
        "required": [],
        "optional": ["filter_name"],
    },
    "hosting_get": {
        "label": "Hospedagem - Recuperar site",
        "method": "GET",
        "required": ["site"],
        "optional": [],
    },
    "hosting_update_status": {
        "label": "Hospedagem - Atualizar status",
        "method": "PUT",
        "required": ["site", "active"],
        "optional": [],
    },
    "hosting_create": {
        "label": "Hospedagem - Criar site",
        "method": "POST",
        "required": ["site", "site_name", "operation_system", "client_id", "product_id", "ftp_login_id", "password"],
        "optional": ["payment_info_id", "confirm_purchase"],
    },
    "hosting_delete": {
        "label": "Hospedagem - Remover site",
        "method": "DELETE",
        "required": ["site"],
        "optional": [],
    },
    "hosting_alias_list": {
        "label": "Hospedagem - Apelido - Listar",
        "method": "GET",
        "required": ["site"],
        "optional": [],
    },
    "hosting_alias_get": {
        "label": "Hospedagem - Apelido - Recuperar",
        "method": "GET",
        "required": ["site", "alias_name"],
        "optional": [],
    },
    "hosting_alias_update": {
        "label": "Hospedagem - Apelido - Atualizar",
        "method": "PUT",
        "required": ["site", "alias_name"],
        "optional": ["seo_redirect", "alias_new_name"],
    },
    "hosting_alias_create": {
        "label": "Hospedagem - Apelido - Criar",
        "method": "POST",
        "required": ["site", "alias_new_name"],
        "optional": ["seo_redirect"],
    },
    "hosting_alias_delete": {
        "label": "Hospedagem - Apelido - Remover",
        "method": "DELETE",
        "required": ["site", "alias_name"],
        "optional": [],
    },
    "hosting_ftp_list": {
        "label": "Hospedagem - FTP - Listar usuarios",
        "method": "GET",
        "required": ["site"],
        "optional": [],
    },
    "hosting_ftp_create": {
        "label": "Hospedagem - FTP - Criar usuario",
        "method": "POST",
        "required": ["site", "login", "password"],
        "optional": ["root_path", "create_dir"],
    },
    "hosting_ftp_update": {
        "label": "Hospedagem - FTP - Atualizar senha",
        "method": "PUT",
        "required": ["site", "ftp_login", "password"],
        "optional": [],
    },
    "hosting_ftp_delete": {
        "label": "Hospedagem - FTP - Remover usuario",
        "method": "DELETE",
        "required": ["site", "ftp_login"],
        "optional": [],
    },
    "hosting_db_list": {
        "label": "Hospedagem - Banco de Dados - Listar",
        "method": "GET",
        "required": ["site"],
        "optional": [],
    },
    "hosting_db_get": {
        "label": "Hospedagem - Banco de Dados - Recuperar",
        "method": "GET",
        "required": ["site", "db_name"],
        "optional": [],
    },
    "hosting_db_create": {
        "label": "Hospedagem - Banco de Dados - Criar",
        "method": "POST",
        "required": ["site", "db_name_new"],
        "optional": [],
    },
    "hosting_db_delete": {
        "label": "Hospedagem - Banco de Dados - Remover",
        "method": "DELETE",
        "required": ["site", "db_name"],
        "optional": [],
    },
    "hosting_db_user_list": {
        "label": "Hospedagem - DB Usuario - Listar",
        "method": "GET",
        "required": ["site", "db_name"],
        "optional": [],
    },
    "hosting_db_user_get": {
        "label": "Hospedagem - DB Usuario - Recuperar",
        "method": "GET",
        "required": ["site", "db_name", "db_login"],
        "optional": [],
    },
    "hosting_db_user_create": {
        "label": "Hospedagem - DB Usuario - Criar",
        "method": "POST",
        "required": ["site", "db_name", "login", "password"],
        "optional": [],
    },
    "hosting_db_user_update": {
        "label": "Hospedagem - DB Usuario - Atualizar",
        "method": "PUT",
        "required": ["site", "db_login", "login", "password"],
        "optional": [],
    },
    "hosting_db_user_delete": {
        "label": "Hospedagem - DB Usuario - Remover",
        "method": "DELETE",
        "required": ["site", "db_name", "db_login"],
        "optional": [],
    },
    "hosting_php_versions": {
        "label": "Hospedagem - PHP - Versoes disponiveis",
        "method": "GET",
        "required": ["site"],
        "optional": [],
    },
    "hosting_php_info": {
        "label": "Hospedagem - PHP - Informacoes",
        "method": "GET",
        "required": ["site"],
        "optional": [],
    },
    "hosting_php_update": {
        "label": "Hospedagem - PHP - Atualizar configuracoes",
        "method": "PUT",
        "required": ["site"],
        "optional": ["data_kv"],
    },
    # ── Dashboard ─────────────────────────────────────────────
    "dashboard_get": {
        "label": "Dashboard - Recuperar dados",
        "method": "GET",
        "required": [],
        "optional": [],
    },
    # ── Template ──────────────────────────────────────────────
    "template_list": {
        "label": "Template - Listar templates",
        "method": "GET",
        "required": [],
        "optional": [],
    },
    # ── Usuarios Administrativos ──────────────────────────────
    "useradmin_create": {
        "label": "Usuario Admin - Criar",
        "method": "POST",
        "required": ["username", "email", "password"],
        "optional": [],
    },
    "useradmin_change_password": {
        "label": "Usuario Admin - Alterar senha",
        "method": "PUT",
        "required": ["username", "password", "actual"],
        "optional": [],
    },
    "useradmin_2fa_config": {
        "label": "Usuario Admin - 2FA - Obter configuracao",
        "method": "GET",
        "required": ["username"],
        "optional": [],
    },
    "useradmin_2fa_enable": {
        "label": "Usuario Admin - 2FA - Ativar",
        "method": "POST",
        "required": ["username", "secret", "code"],
        "optional": [],
    },
    "useradmin_2fa_disable": {
        "label": "Usuario Admin - 2FA - Desativar",
        "method": "DELETE",
        "required": ["username"],
        "optional": [],
    },
    "useradmin_2fa_mandatory_on": {
        "label": "Usuario Admin - 2FA - Ativar obrigatoriedade",
        "method": "POST",
        "required": ["username"],
        "optional": [],
    },
    "useradmin_2fa_mandatory_off": {
        "label": "Usuario Admin - 2FA - Desativar obrigatoriedade",
        "method": "DELETE",
        "required": ["username"],
        "optional": [],
    },
    # ── WebHooks globais ──────────────────────────────────────
    "webhook_list": {
        "label": "WebHook - Listar tipos disponiveis",
        "method": "GET",
        "required": [],
        "optional": [],
    },
    # ── Backup ────────────────────────────────────────────────
    "backup_client_list": {
        "label": "Backup - Listar contas",
        "method": "GET",
        "required": [],
        "optional": ["clientId", "search", "days"],
    },
    "backup_client_get": {
        "label": "Backup - Recuperar conta",
        "method": "GET",
        "required": ["backup_client_id"],
        "optional": [],
    },
    "backup_client_create": {
        "label": "Backup - Criar conta",
        "method": "POST",
        "required": ["clientId", "backupServerId", "backupClientId", "password"],
        "optional": ["timezone", "language"],
    },
    "backup_client_update": {
        "label": "Backup - Atualizar conta",
        "method": "PUT",
        "required": ["backup_client_id"],
        "optional": ["timezone", "language", "data_kv"],
    },
    "backup_client_update_status": {
        "label": "Backup - Atualizar status",
        "method": "PUT",
        "required": ["backup_client_id", "status"],
        "optional": [],
    },
    "backup_client_update_password": {
        "label": "Backup - Alterar senha",
        "method": "PUT",
        "required": ["backup_client_id", "password"],
        "optional": [],
    },
    "backup_client_delete": {
        "label": "Backup - Excluir conta",
        "method": "DELETE",
        "required": ["backup_client_id"],
        "optional": [],
    },
    "backup_routine_list": {
        "label": "Backup - Rotinas - Listar",
        "method": "GET",
        "required": ["backup_client_id"],
        "optional": [],
    },
    "backup_routine_get": {
        "label": "Backup - Rotinas - Exibir",
        "method": "GET",
        "required": ["backup_client_id", "backup_set_id"],
        "optional": [],
    },
    "backup_history_list": {
        "label": "Backup - Historico - Listar",
        "method": "GET",
        "required": ["backup_client_id", "backup_set_id"],
        "optional": [],
    },
    "backup_history_get": {
        "label": "Backup - Historico - Exibir",
        "method": "GET",
        "required": ["backup_client_id", "backup_set_id", "backup_job_id"],
        "optional": [],
    },
    # ── Envios SMTP ───────────────────────────────────────────
    "smtp_report_summary": {
        "label": "SMTP - Resumo de envios",
        "method": "GET",
        "required": ["dateFrom", "dateTo"],
        "optional": ["clientId", "status"],
    },
    "smtp_delivery_list": {
        "label": "SMTP - Listagem de envios",
        "method": "GET",
        "required": ["smtp_client_id"],
        "optional": ["mailbox", "status", "dateFrom", "dateTo", "page", "perPage"],
    },
    "smtp_delivery_get": {
        "label": "SMTP - Retorno especifico de envio",
        "method": "GET",
        "required": ["smtp_client_id", "delivery_id"],
        "optional": [],
    },
    "smtp_report_details": {
        "label": "SMTP - Listagem detalhada (deprecated)",
        "method": "GET",
        "required": ["dateFrom", "dateTo"],
        "optional": ["clientId", "status"],
    },
    "smtp_report_count": {
        "label": "SMTP - Contagem por status",
        "method": "GET",
        "required": ["dateFrom", "dateTo"],
        "optional": ["status"],
    },
    "smtp_report_send_csv": {
        "label": "SMTP - Enviar relatorio por e-mail",
        "method": "POST",
        "required": ["dateFrom", "dateTo"],
        "optional": ["status"],
    },
    "smtp_product_list": {
        "label": "SMTP - Produtos - Listar",
        "method": "GET",
        "required": [],
        "optional": [],
    },
    "smtp_product_get": {
        "label": "SMTP - Produtos - Consultar de cliente",
        "method": "GET",
        "required": ["smtp_client_id"],
        "optional": [],
    },
    "smtp_product_update": {
        "label": "SMTP - Produtos - Alterar de cliente",
        "method": "POST",
        "required": ["smtp_client_id"],
        "optional": [],
    },
    "smtp_message_send": {
        "label": "SMTP - Enviar e-mail via API",
        "method": "POST",
        "required": [],
        "optional": ["data_kv"],
    },
    "smtp_message_status": {
        "label": "SMTP - Consultar status de envio",
        "method": "GET",
        "required": ["message_id"],
        "optional": [],
    },
    # ── Registro de Dominio ───────────────────────────────────
    "domain_reg_check": {
        "label": "Reg. Dominio - Validar disponibilidade",
        "method": "GET",
        "required": ["provider", "domain"],
        "optional": [],
    },
    "domain_reg_get": {
        "label": "Reg. Dominio - Recuperar informacoes",
        "method": "GET",
        "required": ["domain", "clientId"],
        "optional": [],
    },
    "domain_reg_list": {
        "label": "Reg. Dominio - Listar por cliente",
        "method": "GET",
        "required": ["clientId"],
        "optional": [],
    },
    "domain_reg_autorenew": {
        "label": "Reg. Dominio - Renovacao automatica",
        "method": "PUT",
        "required": ["provider", "domain"],
        "optional": [],
    },
    "domain_reg_create": {
        "label": "Reg. Dominio - Registrar dominio",
        "method": "POST",
        "required": ["provider"],
        "optional": ["data_kv"],
    },
    "domain_reg_ns_list": {
        "label": "Reg. Dominio - Nameserver - Listar",
        "method": "GET",
        "required": ["provider", "domain"],
        "optional": [],
    },
    "domain_reg_ns_update": {
        "label": "Reg. Dominio - Nameserver - Atualizar",
        "method": "PATCH",
        "required": ["provider", "domain"],
        "optional": ["data_kv"],
    },
    "domain_reg_org_check": {
        "label": "Reg. Dominio - Organizacao - Verificar",
        "method": "GET",
        "required": ["provider", "document"],
        "optional": [],
    },
}

DNS_ENDPOINTS = {
    "dns_get": {
        "label": "DNS - Recuperar informacoes do dominio",
        "method": "GET",
        "required": ["domain"],
        "optional": [],
    },
    "dns_entry_list": {
        "label": "DNS - Listar entradas da zona",
        "method": "GET",
        "required": ["domain"],
        "optional": ["filters_name", "order_by_field", "order_by_dir"],
    },
    "dns_entry_get": {
        "label": "DNS - Recuperar entrada especifica",
        "method": "GET",
        "required": ["domain", "entry_id"],
        "optional": [],
    },
    "dns_zone_list": {
        "label": "DNS - Listar zonas",
        "method": "GET",
        "required": [],
        "optional": ["filters_name"],
    },
    "dns_zone_create": {
        "label": "DNS - Criar zona",
        "method": "POST",
        "required": ["domain"],
        "optional": [],
    },
    "dns_zone_delete": {
        "label": "DNS - Excluir zona",
        "method": "DELETE",
        "required": ["domain"],
        "optional": [],
    },
    "dns_entry_create": {
        "label": "DNS - Criar entrada na zona",
        "method": "POST",
        "required": ["domain", "dns_name", "dns_type", "dns_value"],
        "optional": ["dns_ttl"],
    },
    "dns_entry_delete": {
        "label": "DNS - Excluir entrada da zona",
        "method": "DELETE",
        "required": ["domain", "entry_id"],
        "optional": [],
    },
}

# Agrupa endpoint IDs por categoria para o seletor de paginas
ENDPOINT_PAGES = {
    "Todas": [],  # preenchido dinamicamente
    "Caixa Postal": [k for k in ENDPOINTS if k.startswith(
        ("app_feature", "mailbox_", "custom_field", "deleted"))],
    "Dominio": [k for k in ENDPOINTS if k.startswith("domain_") and not k.startswith("domain_reg")],
    "Grupos": [k for k in ENDPOINTS if k.startswith("group_")],
    "Clientes": [k for k in ENDPOINTS if k.startswith("client_")],
    "Hospedagem": [k for k in ENDPOINTS if k.startswith("hosting_")],
    "Dashboard / Template": [k for k in ENDPOINTS if k in ("dashboard_get", "template_list")],
    "Usuarios Admin": [k for k in ENDPOINTS if k.startswith("useradmin_")],
    "WebHook / Backup": [k for k in ENDPOINTS if k.startswith(("webhook_", "backup_"))],
    "SMTP": [k for k in ENDPOINTS if k.startswith("smtp_")],
    "Reg. Dominio": [k for k in ENDPOINTS if k.startswith("domain_reg")],
    "DNS": list(DNS_ENDPOINTS.keys()),
}
ENDPOINT_PAGES["Todas"] = [k for cat, ids in ENDPOINT_PAGES.items() if cat != "Todas" for k in ids]
