FIELD_LABELS = {
    "mailbox": "Mailbox",
    "feature": "Feature",
    "mail": "Novo email",
    "displayname": "Display Name",
    "password": "Password",
    "accounttype": "Account Type",
    "forcepasswordchange": "Force Password Change",
    "accountstatus": "Account Status",
    "title": "Title",
    "alias": "Alias",
    "confirm_purchase": "Confirm Purchase",
    "novo_mail": "Novo Mail",
    "name": "Field Name",
    "value": "Value",
    "field_name": "Field Name (existente)",
    "query": "Query",
    "filters_email": "Filter Email",
    "data_kv": "Campos livres (chave=valor por linha)",
    "domain": "Dominio",
    "entry_id": "ID da Entrada",
    "filters_name": "Filtro por nome",
    "order_by_field": "Ordenar por campo (ex: ttl)",
    "order_by_dir": "Direcao (ASC ou DESC)",
    # novos campos
    "backup_id": "ID do Backup",
    "restoreFolders": "Pastas a restaurar (virgula)",
    "restoreDestination": "Pasta de destino",
    "page": "Pagina",
    "perPage": "Itens por pagina",
    "dateFrom": "Data inicio (YYYY-MM-DD)",
    "dateTo": "Data fim (YYYY-MM-DD)",
    "status": "Status",
    "rule_folder": "Pasta (inbox/draft/sent/trash)",
    "rule_policy": "Politica (-1=sem / 0=remover / 1=mover lixeira)",
    "rule_days": "Dias de retencao",
    "client_id": "Client ID",
    "group_mail": "E-mail do grupo",
    "product_id": "ID do produto",
    "product": "Produto (ID)",
    "amount": "Quantidade",
    "reason": "Motivo",
    "webhook_id": "ID do WebHook",
    "url": "URL do WebHook",
    "httpMethod": "Metodo HTTP",
    "webHook": "Tipo de WebHook",
    "filters_httpMethod": "Filtro por metodo HTTP",
    "site": "Site (dominio)",
    "active": "Ativo (true/false)",
    "operation_system": "Sistema operacional",
    "ftp_login_id": "Login FTP inicial",
    "payment_info_id": "ID pagamento",
    "alias_name": "Nome do apelido",
    "alias_new_name": "Novo nome do apelido",
    "seo_redirect": "SEO Redirect (true/false)",
    "ftp_login": "Login FTP",
    "root_path": "Caminho raiz FTP",
    "create_dir": "Criar diretorio (true/false)",
    "db_name": "Nome do banco de dados",
    "db_name_new": "Nome do novo banco de dados",
    "db_login": "Login do usuario do banco",
    "login": "Login",
    "username": "Username",
    "email": "E-mail",
    "actual": "Senha atual",
    "secret": "Secret MFA",
    "code": "Codigo MFA",
    "backup_client_id": "ID da conta de backup",
    "backupServerId": "ID do servidor de backup",
    "backupClientId": "Nome da conta de backup",
    "backup_set_id": "ID da rotina (backup-set)",
    "backup_job_id": "ID da execucao (backup-job)",
    "timezone": "Fuso horario",
    "language": "Idioma",
    "smtp_client_id": "Client ID SMTP",
    "delivery_id": "ID do envio",
    "message_id": "ID da mensagem",
    "provider": "Provedor (ex: 1)",
    "document": "Documento (CNPJ/CPF)",
    "taxNumber": "CNPJ/CPF",
    "parentId": "Parent ID",
    "client_name": "Nome do cliente",
    "cf_label": "Label do campo personalizado",
    "cf_type": "Tipo do campo (string/integer)",
    "filter_name": "Filtro por nome",
    "dns_name": "Nome da entrada DNS",
    "dns_type": "Tipo DNS (A/AAAA/MX/TXT/etc)",
    "dns_value": "Valor da entrada DNS",
    "dns_ttl": "TTL (segundos)",
    "search": "Busca",
    "days": "Dias",
    "clientId": "Client ID (query)",
    "site_name": "Nome do site",
}

SAMPLE_VALUES = {
    "mailbox": "usuario@dominio.com.br",
    "feature": "skybox.enabledeck",
    "mail": "novo@dominio.com.br",
    "displayname": "Nome Completo",
    "password": "NovaSenha@1",
    "accounttype": "44",
    "forcepasswordchange": "false",
    "accountstatus": "disabled",
    "title": "Analista",
    "alias": "apelido@dominio.com.br",
    "confirm_purchase": "true",
    "novo_mail": "renomeado@dominio.com.br",
    "name": "campo_teste",
    "value": "valor",
    "field_name": "campo_teste",
    "query": ".com",
    "filters_email": "usuario@dominio.com.br",
    "data_kv": "campo1=valor1",
    "domain": "dominio.com.br",
    "entry_id": "1440044",
    "filters_name": "dominio.com",
    "order_by_field": "ttl",
    "order_by_dir": "DESC",
    # novos campos
    "backup_id": "abc123",
    "restoreFolders": "Inbox",
    "restoreDestination": "RESTORE_20240101",
    "page": "1",
    "perPage": "50",
    "dateFrom": "2024-01-01",
    "dateTo": "2024-12-31",
    "status": "sent",
    "rule_folder": "inbox",
    "rule_policy": "1",
    "rule_days": "30",
    "client_id": "1",
    "group_mail": "grupo@dominio.com.br",
    "product_id": "22",
    "product": "1",
    "amount": "10",
    "reason": "Outros motivos",
    "webhook_id": "10816",
    "url": "https://webhook.site/example",
    "httpMethod": "POST",
    "webHook": "client_hire_create",
    "filters_httpMethod": "POST",
    "site": "meudominio.com.br",
    "active": "false",
    "operation_system": "linux",
    "ftp_login_id": "usuarioftp",
    "payment_info_id": "100",
    "alias_name": "apelido.com.br",
    "alias_new_name": "novoapelido.com.br",
    "seo_redirect": "false",
    "ftp_login": "usuarioftp",
    "root_path": "/public_html",
    "create_dir": "true",
    "db_name": "meubancodedados",
    "db_name_new": "novobancodedados",
    "db_login": "meulogin",
    "login": "novousuario",
    "username": "useradmin1",
    "email": "admin@dominio.com.br",
    "actual": "SenhaAtual@1",
    "secret": "JBSWY3DPEBLW64TMMQ======",
    "code": "123456",
    "backup_client_id": "123",
    "backupServerId": "1",
    "backupClientId": "nome_da_conta",
    "backup_set_id": "456",
    "backup_job_id": "789",
    "timezone": "GMT-03:00 (BRT)",
    "language": "pt_BR",
    "smtp_client_id": "32232",
    "delivery_id": "32233",
    "message_id": "abc123",
    "provider": "1",
    "document": "54555154000142",
    "taxNumber": "54555154000142",
    "parentId": "1577",
    "client_name": "Meu Primeiro Cliente",
    "cf_label": "Nome do campo",
    "cf_type": "string",
    "filter_name": "meudominio.com",
    "dns_name": "subdominio.dominio.com.br",
    "dns_type": "A",
    "dns_value": "192.168.1.1",
    "dns_ttl": "3600",
    "search": "nome_da_conta",
    "days": "3",
    "clientId": "1",
    "site_name": "meusite.com.br",
}

